// All UI copy in Polish. Keep keys short and grouped by feature.
export const t = {
  app: {
    name: "Linguaflow",
    tagline: "Trenuj akcent z AI",
  },
  common: {
    next: "Dalej",
    back: "Wstecz",
    save: "Zapisz",
    cancel: "Anuluj",
    continue: "Kontynuuj",
    start: "Zaczynaj",
    finish: "Zakończ",
    retry: "Spróbuj ponownie",
    loading: "Ładowanie…",
    error: "Coś poszło nie tak",
    yes: "Tak",
    no: "Nie",
    skip: "Pomiń",
    record: "Nagraj",
    stop: "Zatrzymaj",
    listen: "Posłuchaj",
    score: "Wynik",
  },
  auth: {
    welcomeTitle: "Mów pewnie. Akcentem zachwycaj.",
    welcomeSub: "Trener wymowy oparty o AI i analizę fonemów.",
    signUp: "Załóż konto",
    signIn: "Zaloguj się",
    name: "Twoje imię",
    email: "Twój e-mail",
    password: "Hasło",
    haveAccount: "Masz już konto? Zaloguj się",
    noAccount: "Nie masz konta? Zarejestruj się",
    signOut: "Wyloguj się",
  },
  onboarding: {
    pickLanguageTitle: "Czego chcesz się nauczyć?",
    pickLanguageSub: "Wybierz język, który chcesz trenować.",
    pickAccentTitle: "Wybierz akcent",
    pickAccentSub: "Trenowanie wymowy działa najlepiej z konkretnym akcentem.",
    startLevelTest: "Sprawdźmy Twój poziom",
    startLevelTestSub: "15 krótkich pytań — słownictwo, wymowa i tłumaczenie.",
    levelTestTitle: "Test poziomu",
    questionOf: (n: number, total: number) => `Pytanie ${n} z ${total}`,
    speechPrompt: "Przeczytaj zdanie na głos:",
    translationPrompt: "Przetłumacz to zdanie:",
    yourAnswer: "Twoja odpowiedź",
    submit: "Zatwierdź",
    resultsTitle: "Twój poziom",
    breakdown: "Wyniki według kategorii",
    summary: "Podsumowanie",
    focusAreas: "Na czym się skupić",
    goToApp: "Przejdź dalej",
    vocabulary: "Słownictwo",
    pronunciation: "Wymowa",
    translation: "Tłumaczenie",
  },
  home: {
    greeting: (name: string) => (name ? `Cześć, ${name}!` : "Cześć!"),
    streak: "Dni z rzędu",
    xp: "Punkty",
    level: "Poziom",
    continueModule: "Kontynuuj moduł",
    pickModule: "Wybierz nowy moduł",
    noActiveModule: "Brak aktywnego modułu",
    pickNewModuleCta: "Wybierz moduł",
  },
  modules: {
    suggestTitle: "Co chcesz dzisiaj poćwiczyć?",
    suggestSub: "AI proponuje trzy moduły. Możesz też wpisać własny temat.",
    customLabel: "Lub wpisz swój temat",
    customPlaceholder: "Np. zamawianie pizzy",
    pickThisOne: "Wybierz ten",
    moduleTitle: "Moduł",
    taskCounter: (done: number, total: number) => `${done} z ${total} zadań`,
    taskKindVocab: "Słownictwo",
    taskKindPhrase: "Fraza",
    taskKindFree: "Wypowiedź",
    completedCta: "Ukończ moduł",
    moduleComplete: "Świetnie! Moduł ukończony.",
    nextModule: "Wybierz nowy moduł",
    abandon: "Porzuć moduł",
  },
  task: {
    targetSentence: "Powtarzaj:",
    holdToRecord: "Naciśnij i mów",
    recording: "Słucham…",
    processing: "Analizuję wymowę…",
    yourTranscript: "Twój zapis",
    aiTips: "Wskazówki AI",
    tryAgain: "Powtórz",
    nextTask: "Następne zadanie",
    finishModule: "Zakończ moduł",
    xpEarned: (xp: number) => `+${xp} pkt`,
    vocabularyHeader: "Nowe słownictwo",
  },
  profile: {
    title: "Profil",
    changeLanguage: "Zmień język",
    longestStreak: "Najdłuższa passa",
    totalXp: "Suma punktów",
    currentLevel: "Aktualny poziom",
    detectedLevel: "Wykryty poziom",
    accent: "Akcent",
    signOutConfirm: "Na pewno chcesz się wylogować?",
  },
  errors: {
    micPermission: "Nie udało się uzyskać dostępu do mikrofonu. Sprawdź uprawnienia w ustawieniach.",
    network: "Brak połączenia z serwerem.",
    azureFail: "Nie udało się rozpoznać mowy. Spróbuj ponownie wyraźniej.",
  },
} as const;
