/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AZURE_SPEECH_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AZURE_SPEECH_REGION": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LinguaflowApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENROUTER_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENROUTER_MODEL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_SERVICE_ROLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SUPABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}